spring.application.name=pos-service
spring.datasource.url=jdbc:postgresql://157.10.161.207:5432/nivora-pos-db
spring.datasource.username=postgres
spring.datasource.password=ShaninHanan23
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
jwt.secret=NivoraPOSSecretKey2024VeryLongSecretForHS256Algorithm
jwt.expiration=86400000
